Refactoring UI
Technoculture/Ella pull request #2
Opened 2023-12-06 13:52 UTC by Naveen-g09

Tasks:
1. Refactor code from UI
2. Create Components from Home.tsx

2023-12-06 14:28 UTC, sutyum requested changes
not much to go by yet

2023-12-06 14:28 UTC, sutyum commented on app/ChatCard.tsx
> +import { useState, useEffect, useRef } from "react";
split this file into one file per component

2023-12-06 14:28 UTC, sutyum commented on app.json
> +        "projectId": "dfde4001-b00b-4a77-a028-7d966b8f9e3d"
why?

2023-12-06 14:28 UTC, sutyum commented on app/index.tsx
> +const Home = () => {
simply rename the home.tsx to index.tsx

2023-12-06 18:45 UTC, Naveen-g09 commented on app.json
> +        "projectId": "dfde4001-b00b-4a77-a028-7d966b8f9e3d"
I shall probably add this to gitignore file, as if I don't change productid it won't run on my system

2023-12-07 12:06 UTC, sutyum requested changes
Use tailwind/nativewind to style components unless dealing with a special scenario where tailwind is causing issues

2023-12-07 12:07 UTC, sutyum commented
Overall today's PR has more to read, good start @Naveen-g09

2023-12-07 12:12 UTC, sutyum commented on package-lock.json
`package-lock.json`

2023-12-07 18:11 UTC, sutyum commented
Need to setup eslint as described here: https://docs.expo.dev/guides/using-eslint/
@Naveen-g09

2023-12-08 07:02 UTC, Naveen-g09 commented on package.json
> +    "react-native-animatable": "^1.4.0",
Was trying to add little animation to the card which didn't work

2023-12-08 11:59 UTC, Naveen-g09 commented
This PR contains:
1. individual components
2. Camera functionality
3. Gallery Functionality
4. Eslint Configuration

https://github.com/Technoculture/Ella/assets/76151123/baa3c7e4-7b3e-47bb-bf5c-594e0f89f552

2023-12-08 17:59 UTC, sutyum requested changes
Overall this had a lot to read.

It seems you need to look into a few things to fix the issues:
- the expo router (file based routing) and its relationship with the folder structure
- using cva, cn to write reusable styled components

---

Naming convention needs to be followed more precisely - TitleCase for components, and camelCase for routes and utils

2023-12-08 17:59 UTC, sutyum commented on app/Camera.tsx
you need to be using tailwind instead of custom styling. Before we merge this PR, these all need to be fixed

2023-12-08 17:59 UTC, sutyum commented on app/ChatCard.tsx
> +    <View className={`${baseStyle} ${variantStyle}`}>
go through this: https://medium.com/@gorkemkaramolla/react-tailwind-reuseable-and-customizable-components-with-cva-clsx-and-tailwindmerge-combo-guide-c3756bdbbf16

Use cn as shown here to concatenate style strings, use cva to define stateless components

2023-12-08 17:59 UTC, sutyum commented on app/ChatCard.tsx
> +export function MessageBlob(props: MessageBlobType) {
refactor this with cva, extract out the component into its own file

2023-12-08 17:59 UTC, sutyum commented on app/ChatCard.tsx
This file still has too many components, refactor the components out into their own files in the components dir. Common types or any common helper functions can go in a utils dire

2023-12-08 17:59 UTC, sutyum commented on app/Footer.tsx
> +const styles = StyleSheet.create({
tw

2023-12-08 17:59 UTC, sutyum commented on app/RoundedButton.tsx
> +}: RoundedButtonProps): React.JSX.Element {
Its a good first effort, but see if you can inherit from something more semantically closer - A touchable opacity, or maybe a button

2023-12-08 17:59 UTC, sutyum commented on app/RoundedButton.tsx
> +  className,
```js
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default:
          "bg-primary text-primary-foreground shadow hover:bg-primary/90",
        destructive:
          "bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90",
        outline:
          "border border-input bg-transparent shadow-sm hover:bg-accent hover:text-accent-foreground",
        secondary:
          "bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 rounded-md px-3 text-xs",
        lg: "h-10 rounded-md px-8",
        icon: "h-9 w-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }
```

try to emulate this

2023-12-08 17:59 UTC, sutyum commented on app/_layout.tsx
> -export {
So we don't have a top level Error Boundary now? this is a bad idea, we must have a top level error boundary

2023-12-08 17:59 UTC, sutyum commented on app/audioPlayer.tsx
Same feedback as for the RoundedButton

2023-12-18 08:43 UTC, sutyum requested changes
tailwind only [unless you have a good reason (example: flashlist)].

2023-12-18 08:43 UTC, sutyum commented on app/Footer.tsx
> +  onCallPress: () => Promise<void>;
In scenarios where you are giving a type to something which relates to react, 
- you should either lookup what type is conventionally used in react for such scenarios OR,
- go to grep.app or some typescript for react cheatsheet and follow the examples

2023-12-18 08:43 UTC, sutyum commented on app/Footer.tsx
> +  onCallPress: () => Promise<void>;
https://github.com/typescript-cheatsheets/react

2023-12-18 08:43 UTC, sutyum commented on app/Footer.tsx
> +          <Text style={{ color: "white", fontSize: 18, textAlign: "center" }}>
tailwind

2023-12-18 08:43 UTC, sutyum commented on app/[...missing].tsx
> +        <Link href="/index" style={styles.link}>
use typed routes

2023-12-18 08:43 UTC, sutyum commented on app.d.ts
> +/// <reference types="nativewind/types" />
Add a comment in this to describe why it has been added. A link of where this solution comes from should also be added

2023-12-18 08:43 UTC, sutyum commented on app/index.tsx
> +      style={{ height: screenHeight }}
tailwind

2023-12-18 08:43 UTC, sutyum commented on app/input/Camera.tsx
> +import { Camera as ExpoCamera, CameraType } from "expo-camera";
tailwind

2023-12-18 08:43 UTC, sutyum commented on app/input/CameraScreen.tsx
> +// CameraScreen.tsx
tailwind

2023-12-18 08:43 UTC, sutyum commented on app/input/Gallery.tsx
> +        type: "*/*",
pdf, png, jpg, jpeg, doc, docx, avi, mp4, ...

2023-12-18 08:43 UTC, sutyum commented on components/MessageBlob.tsx
> +export function MessageBlob(props: MessageBlobProps): React.ReactElement {
Use CVA, cn (tw-merge)

2023-12-18 08:43 UTC, sutyum commented on components/RoundedButton.tsx
> +      className={`bg-gray-800 dark:bg-green-950 h-20 w-20 rounded-full items-center justify-center ${className}`}
atleast use cn

2023-12-18 08:43 UTC, sutyum commented on package.json
> +    "lint": "eslint ."
pre-commit: run all 3 (format, lint, type)

2023-12-18 08:43 UTC, sutyum commented on yarn.lock
is this needed by something dowsteam?

2023-12-18 08:45 UTC, sutyum requested changes
tailwind, preview issue, linting issue

2023-12-18 10:32 UTC, Naveen-g09 commented on app/index.tsx
> +      style={{ height: screenHeight }}
resolved for view with tw
but height is coming from variable, is there a way in tw to use?

2023-12-18 11:02 UTC, Naveen-g09 commented on package.json
> +    "lint": "eslint ."
"format-check": "prettier --check \"**/*.{ts,tsx}\"",
    "type-check": "tsc --pretty --noEmit",
    "lint": "eslint ."

2023-12-18 11:10 UTC, Naveen-g09 commented on app/input/Gallery.tsx
> +        type: "*/*",
type: "application/pdf,text/plain,image/*,audio/*,video/*,.doc,.docx"
used all these, any other required?

2023-12-18 13:30 UTC, Naveen-g09 commented on app/[...missing].tsx
> +        <Link href="/index" style={styles.link}>
Is this creating the issue related to build? or
Should I fix this on router-setup pr? , as i still need to understand it

2023-12-20 10:39 UTC, Naveen-g09 commented on app/ChatCard.tsx
> +    <View className={`${baseStyle} ${variantStyle}`}>
this has been moved to AudioPlayer.tsx, resolving it there.

2023-12-20 10:41 UTC, Naveen-g09 commented on app/ChatCard.tsx
> +export function MessageBlob(props: MessageBlobType) {
refactoring in MessageBlob.tsx

2023-12-20 13:13 UTC, sutyum requested changes

2023-12-20 13:13 UTC, sutyum commented on .env.sample
> -OPENAI_API_KEY="..."
revert this

2023-12-20 13:13 UTC, sutyum commented on yarn.lock
is this required?

2023-12-20 13:23 UTC, Naveen-g09 commented on yarn.lock
yes

2023-12-20 13:41 UTC, Naveen-g09 reviewed
Resolved

2023-12-20 13:45 UTC, sutyum approved these changes

2023-12-20 13:46 UTC, merged

2023-12-20 13:46 UTC, sutyum commented
Good start @Naveen-g09 Looking forward to the features you build for Ella